name: Echo Release Notes

on:
  workflow_call:  # allows this workflow to be called by other workflows
  release:
    types: [created, published]

jobs:
  echo-release-notes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo Release Information
        run: |
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Release ID: ${{ github.event.release.id }}"
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Notes:"
          echo "${{ github.event.release.body }}"
          echo "JSON: ${{ toJSON(github.event) }}"
